### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by thisoverride** [Rollphes/BoothManager#2]
Hello I see you using the boothSDK  how contact to you ?

**Comment by Rollphes** [comment]
I am not using your work, BoothSDK.
Initially, before creating this repository, I checked to see if there were any public APIs available from Booth, but there was not much information available, so I thought of scraping to achieve this.
Indeed, I have seen your repository, but I am also developing it to learn programming.
Therefore, I have been using the information in [sdk.booth.config.json](https://github.com/thisoverride/Booth.pm/blob/main/src/lib/core/conf/sdk.booth.config.json) as a reference. I have referred to the Endpoint only.
If there are any problems with this, I would appreciate it if you could point them out to me.
Translated at DeepL.

英語を勉強中なので、もし日本語でのコンタクトができるのであればそちらで連絡をいただければありがたいです。

**Comment by Rollphes** [comment]
P.S.
Although it is named BoothManager, it is actually a package for Unity.
This is a tool for VRChat.

**Comment by thisoverride** [comment]
Hi dont worry ! There is no problem, I just wanted to let you know that I am working on a new version with new features because the first one was not completely finished. I also wanted to let you know that if you develop the same thing in C#, keep me informed so I can add the link to your repo in my README. PS: If you want to use my work, it is 100% open source. :)

**Comment by Rollphes** [comment]
Good morning.
Unfortunately, I believe that BoothSDK and BoothManager have different architectures.
This REPO is not a reprogramming of BoothSDK in C#.
Also, since BoothManager is a UnityTool, I don't think it will be the same even if you reprogram it in the future.
However, your BoothSDK library is a very good one.
I am looking forward to seeing it published in npm as I basically use Typescript.
Good Luck!
